[project]
name = "repoconf"
version = "0.0.0dev1"
description = "Centrally configure your decentralised git repo"
requires-python = ">=3.12"
readme = "README.md"
authors = [
    { name = "Suhas Krishna Srivastava", email = "suhas.srivastava@vaastav.tech" }
]
maintainers = [
    { name = "Suhas Krishna Srivastava", email = "suhas.srivastava@vaastav.tech" }
]
keywords = [
    'config', 'version-control', 'configuration', 'git', 'vcs', 'library', 'version control', 'centralized', 'central'
]
classifiers = [
    "Development Status :: 1 - Planning",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: System Administrators",
    "Topic :: Education",
    "Topic :: Software Development",
    "Topic :: Software Development :: Version Control",
    "Topic :: Software Development :: Version Control :: Git",
    "Topic :: Security",
    "Topic :: Security :: Cryptography",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3 :: Only",
    "Typing :: Typed",
]
license = "Apache-2.0"
license-files = ["LICENSE"]
dependencies = [
    "logician >= 0.0.0.dev12",
    "gitbolt >= 0.0.0.dev14",
    "vt-commons >= 0.0.1.dev10",
    "vt-err-hndlr >= 0.0.0.dev7",
]

[dependency-groups]
lint = ["ruff >= 0.15.8"]
typecheck = ["mypy >= 1.19.1"]
dev = [{include-group = "lint"}, {include-group = "typecheck"}]
doc = ["sphinx >= 9.1.0", "sphinx-argparse >= 0.5.2"]
test = ["pytest >= 9.0.2", "gitbolt[test] >= 0.0.0.dev14"]
cover = [{include-group = "test"}, "pytest-cov >= 7.1.0"]
multitest = ["tox >= 4.51.0"]

[project.urls]
homepage = "https://github.com/Vaastav-Technologies/py-repoconf"
source = "https://github.com/Vaastav-Technologies/py-repoconf"
issues = "https://github.com/Vaastav-Technologies/py-repoconf/issues"

[tool.setuptools.packages.find]
where = ['src']

[tool.pytest.ini_options]
addopts = ["--doctest-modules", # Test all the doctests
    "--doctest-glob=*.md"] # Test doctests included as examples in the md files.
